//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_ObjInteraction : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean ScaleLeft
        {
            get
            {
                return SteamVR_Actions.objInteraction_ScaleLeft;
            }
        }
        
        public virtual SteamVR_Action_Boolean ScaleRight
        {
            get
            {
                return SteamVR_Actions.objInteraction_ScaleRight;
            }
        }
        
        public virtual SteamVR_Action_Pose PoseRight
        {
            get
            {
                return SteamVR_Actions.objInteraction_PoseRight;
            }
        }
        
        public virtual SteamVR_Action_Pose PoseLeft
        {
            get
            {
                return SteamVR_Actions.objInteraction_PoseLeft;
            }
        }
    }
}
